config/routes.rb
Rails.application.routes.draw do

  root 'landing#index'
  get 'landing/index' => 'landing#index', as: :landing

 # get 'student_profiles' => 'student_profiles#index', as: :student_profiles

  #get 'business_profiles' => 'business_profiles#index', as: :business_profiles
  # get 'users/profile'
  get 'admin' => 'admin#index', as: :admin

  resources :business_listings
  resources :business_profiles
  resources :student_profiles
  resources :admin

  devise_for :users, :controllers => {
    :invitations => 'users/invitations',
    :registrations => "users/registrations"
  }

  resources :users, only: [:show]


end

app/models/business_profile.rb
class BusinessProfile < ActiveRecord::Base
	belongs_to :user
	has_many :business_listings

	validates_presence_of :business_name
	validates_uniqueness_of :user_id
end

app/controllers/business_profiles_controller.rb
class BusinessProfilesController < ApplicationController
  load_and_authorize_resource
  #before_action :authenticate_user!
  #before_action :set_business_profile, only: [:show, :edit, :update, :destroy]

  # GET /business_profiles
  # GET /business_profiles.json
  def index
    @business_profiles = BusinessProfile.all
    @business_listings = BusinessListing.all
  end

  # GET /business_profiles/1
  # GET /business_profiles/1.json
  def show
    @business_profiles = BusinessProfile.all
  end

  def view_profile
    @business_profile = BusinessProfile.find(params[:id])
    @business_profile.user_id = current_user.id
  end

  # GET /business_profiles/new
  def new
    @business_profile = BusinessProfile.new
  end

  # GET /business_profiles/1/edit
  def edit
    @business_profiles = BusinessProfile.all
  end

  # POST /business_profiles
  # POST /business_profiles.json
  def create
    @business_profile = BusinessProfile.new(business_profile_params)
    @business_profile.user_id = current_user.id
    
    respond_to do |format|
      if @business_profile.save
        format.html { redirect_to @business_profile, notice: 'Business profile was successfully created.' }
        format.json { render :show, status: :created, location: @business_profile }
      else
        format.html { render :new }
        format.json { render json: @business_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /business_profiles/1
  # PATCH/PUT /business_profiles/1.json
  def update
    respond_to do |format|
      if @business_profile.update(business_profile_params)
        format.html { redirect_to @business_profile, notice: 'Business profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @business_profile }
      else
        format.html { render :edit }
        format.json { render json: @business_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /business_profiles/1
  # DELETE /business_profiles/1.json
  def destroy
    @business_profile.destroy
    
    respond_to do |format|
      format.html { redirect_to business_profiles_url, notice: 'Business profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business_profile
      @business_profile = BusinessProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_profile_params
      params.require(:business_profile).permit(:business_id, :user_id, :business_name, :url_of_business, :description_business)
    end
  
end

app/helpers/business_profiles_helper.rb
module BusinessProfilesHelper
end

app/views/business_profiles/_form.html.erb
<div class="business-prof-form">


<% if user_signed_in? and current_user and current_user.type_of_user == "business" %>
<h2>Edit your Profile</h2>
<% elsif user_signed_in? and current_user and current_user.type_of_user == "admin" %>
<h2>Edit <%= @business_profile.business_name %>'s Profile</h2>
<% end %>



<%= simple_form_for (@business_profile), :html => {:class => "form-horizontal center"}  do |f| %>
  <% if @business_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business_profile.errors.count, "error") %> prohibited this business_profile from being saved:</h2>

      <ul>
      <% @business_profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-container new-bus-prof-form">
 
 <div class="form-group">
    <%= f.label :business_name, "Business Name", class: "col-md-4 control-label" %>
    <div class="col-md-8">
      <%= f.text_field :business_name, :maxlength => 50, class: "form-control", :placeholder => 'Name of Company' %>
      </div>
    </div>
<br>
      <div class="form-group">
    <%= f.label :url_of_business, "Company Website", class: "col-md-4 control-label" %>
    <div class="col-md-8">
      <%= f.text_field :url_of_business, :maxlength => 200, class: "form-control", :placeholder => 'Website' %>
      </div>
    </div>

<br>
  <div class="form-group">
    
    <%= f.label :description_business, "Type of Business", class: "col-md-4 control-label" %>
    <div class="col-md-8">
      <%= f.text_area :description_business, :maxlength => 140, :rows => 3, class: "form-control", :placeholder => 'Put what type of business you are such as development, finance, games, etc ' %>
      </div>

  </div>
  <br>
  <br>

  <%  if can? :edit, BusinessProfile %>
    <div class="login-field new-bus-prof-button">
      <%= f.submit class: "button" %>
    </div>
  <% end %>

</div>

<% end %>

</div>

app/views/business_profiles/edit.html.erb
<%= render 'form' %>

app/views/business_profiles/index.html.erb
<div class="instructions">
	<h1>Business Profiles</h1>
	<p>A list of businesses who are looking to employ coders. To view the job opportunities that a business has to offer, click the 'View jobs' link in the chosen business profile.</p>
</div>

<div class="iso_sort">
	<button id='sortNameAsc'>Ascending </button>
	<button id='sortNameDesc'>Descending</button>
</div>


<div class='biz_flex_index'>
	<% @business_profiles.each do |business_profile| %>
	<%= link_to(business_profile, class: "item card_index", data: { name: business_profile.business_name }) do %>

		<h3> <%= business_profile.business_name %></h3>
		<p><%= business_profile.description_business %></p>

	<% end %>
	<% end %>
</div>

app/views/business_profiles/new.html.erb
<h1 class="new-bus-prof-header">New Business Profile</h1>

<div class="instructions_long">
<p>Hello and welcome to the Digital Jersey Recruitment Platform! Below fill in your company details. After you create your profile in the navigation bar you can add open jobs you are looking to fill at your organization. Also in the navigation bar you can checkout students of the Digital Jersey Coding Programs profiles. You can contact job seekers if you are interested in hiring them. If a student has 'already sponsored' at the top of their page it means they have already found a job. If you would like to sponsor a student to come work for you after the program is complete please contact <a href='mailto:tom@gmail.com'>Tom Hacquoil.</a> 
</div>

<%= render 'form' %>

app/views/business_profiles/show.html.erb
<br>
<br>
<br>
<br>
   <% if user_signed_in? and current_user and current_user.type_of_user == "business" %>

<div class="business-profile-header">
  <h2>My Profile</h2> <%  if can? :edit, BusinessProfile %>
  <%= link_to 'Edit Profile', edit_business_profile_path(@business_profile),  :class => "edit_profiles_biz" %>
<% end %>
</div>

<div class="business-profile-info">
  <ul>
    <li><strong>Business Name:</strong>  <%= @business_profile.business_name %></li>
    <li><strong>Company Website:</strong>  <%= @business_profile.url_of_business %></li>
    <li><strong>Business Sector:</strong>  <%= @business_profile.description_business %></li>
  </ul>
</div>

<div class="job-listing-instructions">
  <h2>My job listings</h2>
  <p><%= link_to 'Post a new job listing', new_business_listing_path %></p>
</div>

<% end %>

<% if user_signed_in? and current_user and current_user.type_of_user == "admin" %>

<div class="business-profile-header">
  <h2>You are viewing <%= @business_profile.business_name %>'s Profile</h2> <%  if can? :edit, BusinessProfile %>
  <%= link_to 'Edit Profile', edit_business_profile_path(@business_profile),  :class => "edit_profiles_biz" %>
<% end %>
</div>

<div class="business-profile-info">
  <ul>
    <li><strong>Business Name:</strong>  <%= @business_profile.business_name %></li>
    <li><strong>Company Website:</strong>  <%= @business_profile.url_of_business %></li>
    <li><strong>Business Sector:</strong>  <%= @business_profile.description_business %></li>
  </ul>
</div>

<div class="job-listing-instructions">
  <h2><%= @business_profile.business_name %>'s job listings</h2>

</div>
<% end %>
 
<% if @business_profile.business_listings.empty?  %>
  
   <div class="instructions_two"> There are no job listings for this company. Please check back at a later date.</div>
  </div>


<% else %>
  <div class='biz_flex'>
    <% @business_profile.business_listings.each do |business_listing| %>
      <div class='bottom_card'>
        <p>
          <h4> <%= business_listing.title %></h4>
          <p class='created'> Job created: <%= business_listing.created_at %></p>
        </p>
        <p>
          <% if business_listing.full_time == true %>
            <strong> <%= 'Full Time' %></strong>
          <% end %>
          <% if business_listing.part_time == true %>
            <strong> <%= 'Part Time' %> </strong>
          <% end %>
          <% if business_listing.contract == true %>
            <strong> <%= 'Contract' %> </strong>
          <% end %>
        </p>
        <p>
          <strong>Skills:</strong>
          <%= business_listing.skills_wanted %>
        </p>
        <p>
          <%= business_listing.job_description %>
        </p>
        <p>
          <strong>Contact:</strong>
          <a href='mailto:<%= business_listing.contact_email %>'><%= business_listing.contact_email %></a>
        </p>
        <%  if can? :destroy, BusinessListing %>
          <%= link_to 'Delete Job', business_listing_path(business_listing), :method => :delete  %>
        <% end %>
        <%  if can? :edit, BusinessListing %>
          <%= link_to 'Edit Job', edit_business_listing_path(business_listing) %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>
<%  if can? :manage, :all %>
  <%= link_to 'Delete Profile', @business_profile,  :method => :delete,  :class => "edit_profiles_destroy_biz"  %>
<% end %>