config/routes.rb
Rails.application.routes.draw do

  root 'landing#index'
  get 'landing/index' => 'landing#index', as: :landing

 # get 'student_profiles' => 'student_profiles#index', as: :student_profiles

  #get 'business_profiles' => 'business_profiles#index', as: :business_profiles
  # get 'users/profile'
  get 'admin' => 'admin#index', as: :admin

  resources :business_listings
  resources :business_profiles
  resources :student_profiles
  resources :admin

  devise_for :users, :controllers => {
    :invitations => 'users/invitations',
    :registrations => "users/registrations"
  }

  resources :users, only: [:show]


end

app/models/student_profile.rb
class StudentProfile < ActiveRecord::Base
	belongs_to :user
	validates_presence_of :first_name, :last_name
	 validates_uniqueness_of  :user_id
end

app/controllers/student_profiles_controller.rb
class StudentProfilesController < ApplicationController
  load_and_authorize_resource
  #before_action :set_student_profile, only: [:show, :edit, :update, :destroy]

  # GET /student_profiles
  # GET /student_profiles.json
  def index
    @student_profiles = StudentProfile.all
    @business_profiles = BusinessProfile.all
  end

  # GET /student_profiles/1
  # GET /student_profiles/1.json
  def show
    
    @business_profiles = BusinessProfile.all
  end

  # GET /student_profiles/new
  def new
    @student_profile = StudentProfile.new
  end


#restriction ability to only view your own profile
  def view_profile
    @student_profile = StudentProfile.find(params[:id])
    @student_profile.user_id = current_user.id
  end

  # GET /student_profiles/1/edit
  def edit
    @business_profiles = BusinessProfile.all
  end



  # POST /student_profiles
  # POST /student_profiles.json
  def create
    @student_profile = StudentProfile.new(student_profile_params)
    @student_profile.user_id = current_user.id

    respond_to do |format|
      if @student_profile.save
        format.html { redirect_to @student_profile, notice: 'Student profile was successfully created.' }
        format.json { render :show, status: :created, location: @student_profile }
      else
        format.html { render :new }
        format.json { render json: @student_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /student_profiles/1
  # PATCH/PUT /student_profiles/1.json
  def update
    @business_profiles = BusinessProfile.all
    respond_to do |format|
      if @student_profile.update(student_profile_params)
        format.html { redirect_to @student_profile, notice: 'Student profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @student_profile }
      else
        format.html { render :edit }
        format.json { render json: @student_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_profiles/1
  # DELETE /student_profiles/1.json
  def destroy
    @student_profile.destroy
    respond_to do |format|
      format.html { redirect_to student_profiles_url, notice: 'Student profile was successfully destroyed.' }
      format.json { head :no_content }
    end
    @business_profiles = BusinessProfile.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_profile
      @student_profile = StudentProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_profile_params
      params.require(:student_profile).permit(:student_id, :user_id, :first_name, :last_name, :github_url, :profile_img, :short_description, :long_decription, :skills, :part_time, :full_time, :contract, :public, :sponsor, :ruby, :year, :rails, :sql, :html, :css, :three_descriptive_words, :website)
    end
end

app/helpers/student_profiles_helper.rb
module StudentProfilesHelper
end

app/views/student_profiles/_form.html.erb
<%= simple_form_for (@student_profile), :html => {:class => "form-horizontal center"} do |f| %>
  <% if @student_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student_profile.errors.count, "error") %> prohibited this student_profile from being saved:</h2>
      <ul>
        <% @student_profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <br>
  <div class="form-container">
    <div class="form-group">
      <%= f.label :first_name, "First name", class: "col-md-4 control-label" %>
      <div class="col-md-8">
        <%= f.text_field :first_name, class: "form-control" %>
      </div>
    </div>
    <br>
    <div class="form-group">
      <%= f.label :last_name, "Last name", class: "col-md-4 control-label" %>
      <div class="col-md-8">
        <%= f.text_field :last_name, class: "form-control" %>
      </div>
    </div>
    <br>
    <div class="form-group">
      <%= f.label :three_descriptive_words, "3 Words", class: "col-md-4 control-label" %>
      <div class="col-md-8">
        <%= f.text_field :three_descriptive_words, class: "form-control", :placeholder => 'Describe yourself in three descriptive words' %>
      </div>
    </div>
    <br>
    <div class="form-group">
      <%= f.label :github_url, "Github", class: "col-md-4 control-label" %>
      <div class="col-md-8">
        <%= f.text_field :github_url, class: "form-control", :placeholder => 'Link to your github profile' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :website, "Website", class: "col-md-4 control-label" %>
      <div class="col-md-8">
        <%= f.text_field :website, class: "form-control", :placeholder => 'If you have a personal website, blog, etc link to it here. No "http://" needed' %>
      </div>
    </div>
    <br>
    <div class="form-group">
      <%= f.label :short_description, "Short description", class: "col-md-4 control-label" %>
      <div class="col-md-8">
        <%= f.text_area :short_description, :maxlength => 110, :rows => 4, class: "form-control", :placeholder => 'Write a short 2 sentence description of yourself'  %>
      </div>
    </div>
    <br>
    <div class="form-group">
      <%= f.label :long_decription, "About You", class: "col-md-4 control-label" %>
      <div class="col-md-8">
        <%= f.text_area :long_decription, :rows => 15, class: "form-control", :placeholder => 'Write about yourself explaining why someone should hire you. Be creative, you can use HTML tags such as strong, img, etc ' %>
      </div>
    </div>
    <br>
    <div class="form-group">
      <%= f.label :skills, "Skills", class: "col-md-4 control-label" %>
      <div class="col-md-8">
        <%= f.text_area :skills, :rows => 8, class: "form-control", :placeholder => 'List your relevant skills', :rows => 8 %>
      </div>
    </div>
    <br>
    <div class="form-group">
      <%= f.label :ruby, "Ruby", class: "col-md-4 control-label" %>
      <div class="col-md-8">
        <%= f.text_field :ruby, class: "form-control", :placeholder => 'Rate your Ruby skills out of 100' %>
      </div>
    </div>
    <br>
    <div class="form-group">
      <%= f.label :rails, "Rails", class: "col-md-4 control-label" %>
      <div class="col-md-8">
        <%= f.text_field :rails, class: "form-control", :placeholder => 'Rate your Rails skills out of 100 ' %>
      </div>
    </div>
    <br>
    <div class="form-group">
      <%= f.label :sql, "SQL", class: "col-md-4 control-label" %>
      <div class="col-md-8">
        <%= f.text_field :sql, class: "form-control", :placeholder => 'Rate your SQL skills out of 100 ' %>
      </div>
    </div>
    <br>
    <div class="form-group">
      <%= f.label :html, "HTML5", class: "col-md-4 control-label" %>
      <div class="col-md-8">
        <%= f.text_field :html, class: "form-control", :placeholder => 'Rate your HTML5 skills out of 100' %>
      </div>
    </div>
    <br>
    <div class="form-group">
      <%= f.label :css, "CSS3", class: "col-md-4 control-label" %>
      <div class="col-md-8">
        <%= f.text_field :css, class: "form-control", :placeholder => 'Rate your CSS3 skills out of 100 ' %>
      </div>
    </div>
    <br>
    <br>
    <div class="form-group">
      <%= f.label :year, class: "col-md-4 control-label" %>
      <div class="col-md-8">
        <%= f.select(:year, options_for_select([['2014', 1],['2015', 2],['2016', 3],['2017', 4],['2018', 5],['2019', 6]]), class: "form-control") %>
      </div>
      <br>
      <br>
      <div class="boxes_for_form">
        <div class="checkbox">
          <%= f.check_box :part_time %> Part Time - willing to take a part time position?
  </div>
        <br>
        <div class="checkbox">
          <%= f.check_box :full_time %> Full Time - willing to take a full time position?
  </div>
        <br>
        <div class="checkbox">
          <%= f.check_box :contract %> Contract - willing to take a contract time position?
  </div>
        <br>
        <% if user_signed_in? and current_user and current_user.type_of_user == "admin" %>
          <div class="checkbox">
            <%= f.check_box :sponsor %> Sponsor - admin check if student is already sponsored
  
  
    <% end %>
        </div>
      </div>
    </div>
    <br>
    <br>
    <br>
    <div class="login-field">
      <%= f.submit class: "button" %>
    </div>
  </div>
<% end %>

app/views/student_profiles/edit.html.erb
<br>
<br>
<br>
<br>
<br>
<br>

<%= render 'form' %>

app/views/student_profiles/index.html.erb
<div class="instructions">
	<p> Below view Coding Program Students who are seeking a job. Remember you can also sponsor students to learn skills and employ them within 6 months. To sponsor a student or to find out more e-mail Tom Hacquoil at <a href="mailto:tom@hacquoil.com">tom@hacquoil.com</a>. In the navigation bar you can find links to set your company profile and post jobs.</p>
</div>



<div class="iso_sort">
	<button id='sortNameAsc'>Ascending</button>
	<button id='sortNameDesc'>Descending</button>
</div>
<div class='student_flex_index'>
	<% @student_profiles.each do |student_profile| %>
	<%= link_to(student_profile, class: "item card_index_student", data: { name: student_profile.last_name }) do %>

		<h4 class="student_name"><%= student_profile.first_name %></h4>
		<p><%= student_profile.three_descriptive_words %></p>
		<p><%= image_tag avatar_url(student_profile), :class => "s_img_index" %></p>

		<p class="three_words"> <%= student_profile.short_description %></p>


	<% end %>
<% end %>

</div>

app/views/student_profiles/new.html.erb
<br>
<br>
<br>
<br>
<div class="instructions_long">
<p>Hello and welcome to the Digital Jersey Recruitment Platform! Below fill in your details. The "About You" section below is 'html safe' so feel free to personalize it with white listed html tags. (including img, h3, strong, etc) After you create your profile you will be able to see businesses in the area who are currently hiring. To get the best results it is recommended to fill in all fields with as much detail as possible. 
</div>

<div class="form">
<%= render 'form' %>
</div>

app/views/student_profiles/show.html.erb
 <header>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <!-- <img class="img-responsive" src='<%= image_tag avatar_url(@student_profile) %>'> -->
                    <div class="intro-text">
                        <p class="name">  <%= @student_profile.first_name %><br> <%= @student_profile.last_name %></p>
                        <p><%= image_tag avatar_url(@student_profile), :class => "s_img" %></p>
                        <% if @student_profile.sponsor == true %>
                            <p class="sponsor">Student already has a sponsor</p>
                        <% end %>


                        <br>
                        <br>
                        <br>
                        <br>
                       <!-- <p><hr class="star-light"></p> --> 
                        
                    </div>
                </div>
            </div>
        </div>
    </header>

<section id="portfolio">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>Skills</h2>
                    <hr class="star-primary">
                </div>
            </div>
                <div id="Proficiencies">
    
       

    <div id="ProficienciesTop"><p>Ruby</p></div><!-- END ProficienciesTop -->

    <div id="ProficienciesBottom">
      <div class="progress">
        <div class="jquery progress-bar progress-bar-info" role="progressbar" style="width: 0%" data-percent="<%= @student_profile.ruby %>"></div>
      </div>
    </div><!--END ProficienciesBottom-->
    <div id="ProficienciesTop"><p>Rails</p></div><!-- END ProficienciesTop -->

    <div id="ProficienciesBottom">
      <div class="progress">
        <div class="jquery progress-bar progress-bar-info" role="progressbar" style="width: 0%" data-percent="<%= @student_profile.rails %>"></div>
      </div>
    </div><!--END ProficienciesBottom-->
    <div id="ProficienciesTop"><p>SQL</p></div><!-- END ProficienciesTop -->

    <div id="ProficienciesBottom">
      <div class="progress">
        <div class="jquery progress-bar progress-bar-info" role="progressbar" style="width: 0%" data-percent="<%= @student_profile.sql %>"></div>
      </div>
    </div><!--END ProficienciesBottom-->
    <div id="ProficienciesTop"><p>HTML5</p></div><!-- END ProficienciesTop -->

    <div id="ProficienciesBottom">
      <div class="progress">
        <div class="jquery progress-bar progress-bar-info" role="progressbar" style="width: 0%" data-percent="<%= @student_profile.html %>"></div>
      </div>
    </div><!--END ProficienciesBottom-->
    <div id="ProficienciesTop"><p>CSS</p></div><!-- END ProficienciesTop -->

    <div id="ProficienciesBottom">
      <div class="progress">
        <div class="jquery progress-bar progress-bar-info" role="progressbar" style="width: 0%" data-percent="<%= @student_profile.css %>"></div>
      </div>
    </div><!--END ProficienciesBottom-->
</div>


             <p class="s_skills"> <%= @student_profile.skills %></p>
    </section>
<section class="success" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>About</h2>
                    <hr class="star-light">
                </div>
            </div>
            
                    <p class="s_skills">  <%= sanitize @student_profile.long_decription.html_safe %></p>
                
            
    </section>
 <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>Contact <%= @student_profile.first_name %></h2>
                    <hr class="star-primary">
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19. -->
                    <!-- The form should work on most web servers, but if the form is not working you may need to configure your web server differently. -->
                    <form name="sentMessage" id="contactForm" novalidate>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <p> GitHub: <%= link_to @student_profile.github_url, "http://#{@student_profile.github_url}" %> </p>
                                
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <p>Email: <a href='mailto:<%= @student_profile.user.email %>'><%= @student_profile.user.email %></p></a>
                               
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <p>
                                    Website: <%= link_to @student_profile.website, "http://#{@student_profile.website}" %></p>
                                
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <p>Availability:  <% if @student_profile.full_time == true %>
                                                        <strong> <%= 'Full Time' %></strong>
                                                <% end %>
                                                <% if @student_profile.part_time == true %>
                                                        <strong> <%= 'Part Time' %> </strong>
                                                <% end %>
                                                <% if @student_profile.contract == true %>
                                                        <strong> <%= 'Contract' %> </strong>
                                                <% end %>
                                                                                       

                                                    </p>
                                
                            </div>
                        </div>
                        <br>
                        <div id="success"></div>
                        <div class="row">
                            <div class="form-group col-xs-12">
                               
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

<%  if can? :edit, StudentProfile %>
  <%= link_to 'Edit ', edit_student_profile_path(@student_profile),  :class => "edit_profiles" %>
<% end %>

<%  if can? :manage, :all %>
  <%= link_to 'Delete ', @student_profile,  :method => :delete,  :class => "edit_profiles_destroy"  %>
<% end %>