config/routes.rb
Rails.application.routes.draw do

  root 'landing#index'
  get 'landing/index' => 'landing#index', as: :landing

 # get 'student_profiles' => 'student_profiles#index', as: :student_profiles

  #get 'business_profiles' => 'business_profiles#index', as: :business_profiles
  # get 'users/profile'
  get 'admin' => 'admin#index', as: :admin

  resources :business_listings
  resources :business_profiles
  resources :student_profiles
  resources :admin

  devise_for :users, :controllers => {
    :invitations => 'users/invitations',
    :registrations => "users/registrations"
  }

  resources :users, only: [:show]


end

app/views/layouts/application.html.erb
<head>

<title>Find Jersey Coders</title>
<link href='https://fonts.googleapis.com/css?family=PT+Sans' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Roboto:400,700' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.4/material.indigo-pink.min.css">

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">

</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-custom">
	<!-- Preloader -->
	<div id="preloader">
	  <div id="load"></div>
	</div>

  <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">

      <div class="logo">
        <p class="logo-text">Recruitment<br>Platform</p>
        <%= image_tag 'logo.png', class: "logo-img" %>
      </div>
      <div></div>
<!--         <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
            <i class="fa fa-bars"></i>
        </button>
        <a class="navbar-brand" href="index.html"></a>
      </div>
 -->
<!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
      <ul class="nav navbar-nav">

        <li class="active">
          <% if user_signed_in? and current_user and current_user.type_of_user == "student" %>
            <%= link_to('Home', business_profiles_path) %>
          <% elsif user_signed_in? and current_user and current_user.type_of_user == "business" %>
            <%= link_to('Home', student_profiles_path) %>
          <% elsif user_signed_in? and current_user and current_user.type_of_user == "admin" %>
            <%= link_to('Home', admin_path) %>
          <% end %>
        </li>

        <li>
          <% if current_page?('/') or current_page?('/landing/index') %>
            <a href="#service">Why Join?</a>
          <% end %>
        </li>

    		<li>
          <% if current_page?('/') or current_page?('/landing/index') %>
            <a href="#about">Our Students</a>
          <% end %>
        </li>

        <li>   
          <% if user_signed_in? and current_user and current_user.type_of_user == "admin" %>
            <% mailer_all = [] %>
            <% @business_profiles.each do |business_profile| %>
                 <% mailer_all.append(business_profile.user.email) %>
            <% end %>
            <a href='mailto:<%= mailer_all.join(",") %>'>Mail All</a>
          <% end %>
        </li>

        <li>
         <% if user_signed_in? and current_user and current_user.type_of_user == "business" %>
           <%= link_to('Post new job', new_business_listing_path, class: 'business-profile-button') %>
         <% end %>
        </li>

        <li>
          <% if user_signed_in? and current_user and current_user.type_of_user == "student" %>
            <%= link_to('My Profile', current_user, class: 'student-profile-button') %>
          <% elsif user_signed_in? and current_user and current_user.type_of_user == "business" %>
            <%= link_to('My Profile', current_user, class: 'business-profile-button') %>
          <% end %>
        </li>

        <li class="dropdown">
          <% if user_signed_in? %>
            <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
          <% else %>
            <%= link_to('Login', new_user_session_path, class: "login") %>
        <% end %>
              
      </ul>
    </div>
  </nav>
	

<%= yield %>

<br>
<br>

<footer>
  <div>
    <ul>
      <li class="copyright">Copyright &#0169; 2015 Digital Jersey Limited</li>
      <div class="creators">
      <li>Ben Whitley</li>
      <li>Dan Le Cornu</li>
      <li>Morti Alexandru</li>
      <li>Christine Harris</li>
      </div>
    </ul>
  </div>
</footer>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DJ Recruitment Platform</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

</head>

<body>

	<%= yield %>

</body>
</html>